enabled: true
mode: VEIN
goldOre:
    rate: 100
    replacement: STONE
diamondOre:
    rate: 100
    replacement: STONE
ironOre:
    rate: 100
    replacement: STONE
lapisOre:
    rate: 100
    replacement: STONE
coalOre:
    rate: 100
    replacement: STONE
redstoneOre:
    rate: 100
    replacement: STONE
quartzOre:
    rate: 100
    replacement: STONE